---
name: 'compile, test and build image on push'

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'doc/**'
      - 'documentation/**'
      - '*.md'
      - '*.adoc'
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.3.0

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: lambda
          path: ./build/function.zip

  deploy:
    runs-on: 'ubuntu-latest'
    needs: build-gradle-project
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'
      - uses: actions/download-artifact@v4
        with:
          name: lambda
      - name: Update lambda function code
        run: |
          aws lambda update-function-code --publish --function-name copy-ssh-to-s3 --zip-file fileb://$(pwd)/function.zip
