---
name: 'compile, test on push on branch'

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'doc/**'
      - 'documentation/**'
      - '*.md'
      - '*.adoc'

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.2.2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build
